name: app_ui
publish_to: none
version: 0.1.0
environment:
  sdk: '>=3.10.0-0 <4.0.0'
dependencies:
  flutter: { sdk: flutter }
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.3.3
  iconsax_plus: ^1.0.0
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
dev_dependencies:
  flutter_test: { sdk: flutter }
  very_good_analysis: ^7.0.0
  bloc_test: ^10.0.0
flutter:
  uses-material-design: true
